apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: mycluster1
  namespace: demo-1
spec:
  expose:
    nodePort:
      enabled: true
  agents: 0
  mode: shared
  persistence:
    type: dynamic
    storageClassName: local-path
  servers: 3
  serviceCIDR: 10.43.0.0/16
  tlsSANs:
  - 3.92.145.113.sslip.io
  version: v1.32.1-k3s1