apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: mycluster2
  namespace: demo-2
spec:
  expose:
    nodePort:
      enabled: true
  agents: 0
  mode: shared
  persistence:
    type: dynamic
    storageClassName: local-path
  servers: 3
  serviceCIDR: 10.43.0.0/16
  tlsSANs:
  - 3.87.157.111.sslip.io
  version: v1.30.5-k3s1