apiVersion: k3k.io/v1alpha1
kind: Cluster
metadata:
  name: myclusteringress
  namespace: demo-1
spec:
  agents: 0
  expose:
    ingress:
      enabled: true
      ingressClassName: "nginx"
  mode: shared
  persistence:
    storageRequestSize: 1G
    type: ephermal
  servers: 1
  serviceCIDR: 10.43.0.0/16
  tlsSANs:
  - 3.81.87.166.sslip.io
  version: v1.26.1-k3s1
