# Stage 1: Builder
FROM node:18 AS builder

WORKDIR /app

COPY . .

RUN npm install && npm run build

# Stage 2: Final
FROM node:18

WORKDIR /app
RUN npm install express
COPY --from=builder /app/dist ./dist
COPY server.js .

CMD ["node", "server.js"]