apiVersion: v1
kind: LimitRange
metadata:
  name: pod-resource-limits
spec:
  limits:
  - default:
      cpu: "0.2"
      memory: "200Mi"
    defaultRequest:
      cpu: "0.1"
      memory: "100Mi"
    max:
      cpu: "0.2"
      memory: "200Mi"
    type: Container

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespace-resource-quota
spec:
  hard:
    requests.cpu: "0.6"
    requests.memory: "600Mi"
    limits.cpu: "0.6"
    limits.memory: "600Mi"